
resource "amenesik_beam" "mybeam" { 
	template = "template"
	program  = "mybeam-template"
	domain   = "openabal.com"
	region   = "any"
	category = "any"
	param    = "none"
	data     = [
		# beam document tags
		{ path = "tag.Title", value="My New Beam Document" },
		{ path = "tag.SubTitle", value="Generated by Terraform" },
		{ path = "tag.Author", value="Iain James Marshall" },
		{ path = "tag.Zone", value="any" },
		{ path = "tag.Provider", value="any" },
		{ path = "tag.Domain", value="openabal.com" },
		{ path = "tag.Probe", value="memory-free" },
		{ path = "tag.Probe", value="disk-free" },
		{ path = "tag.Probe", value="load-average" },
		{ path = "tag.Probe", value="net-rx" },
		{ path = "tag.Probe", value="net-tx" },

		# template specific type WebServer
		{ path = "type.1.name", value = "WebServer" },
		{ path = "type.1.create", value = "wget https://phoenix.amenesik.com/aec/beam/amenesik/install-web-server.sh; bash ./install-web-server.sh" },
		{ path = "type.1.start", value = "bash ./install-web-server.sh" },
		{ path = "type.1.delete", value = "wget https://phoenix.amenesik.com/aec/beam/amenesik/delete-web-server.sh; bash ./delete-web-server.sh" },
		{ path = "type.1.tcp_port", value = "9990" },
		{ path = "type.1.tcp_port", value = "443"  },
		{ path = "type.1.tcp_port", value = "3306" },

		# memory-free probe
		{ path = "probe.1.name", value = "memory-free" },
		{ path = "probe.1.metric", value = "memory:free" },
		{ path = "probe.1.condition", value = "gr" },
		{ path = "probe.1.threshold", value = "0" },
		{ path = "probe.1.type", value = "OCCISCRIPT" },
		{ path = "probe.1.value", value = "both" },
		{ path = "probe.1.behaviour", value = "activity" },

		# disk-free probe
		{ path = "copy.probe", "value" = "1" },
		{ path = "probe.last.name", value = "disk-free" },
		{ path = "probe.last.metric", value = "disk:free" },
		{ path = "probe.last.threshold", value = "20" },

		# load-average probe
		{ path = "copy.probe", "value" = "1" },
		{ path = "probe.last.name", value = "load-average" },
		{ path = "probe.last.metric", value = "load:average:1" },
		{ path = "probe.1.condition", value = "ge" },

		# net-rx probe
		{ path = "copy.probe", "value" = "1" },
		{ path = "probe.last.name", value = "net-rx" },
		{ path = "probe.last.metric", value = "net:eth0:rx:rate" },
		{ path = "probe.1.condition", value = "ge" },

		# net-tx probe
		{ path = "copy.probe", "value" = "1" },
		{ path = "probe.last.name", value = "net-tx" },
		{ path = "probe.last.metric", value = "net:eth0:tx:rate" },
		{ path = "probe.1.condition", value = "ge" },

		# beam document nodes 1 : database hardware
		{ path = "node.1.name", value = "dbhwa" },
		{ path = "node.1.type", value = "Compute" },
		{ path = "node.1.description", value = "hardware node generated by terraform BEAM resource" },
		{ path = "node.1.host.num_cpus", value = "8" },
                { path = "node.1.host.mem_size", value = "32G" },
                { path = "node.1.host.disk_size", value = "i110G" },
                { path = "node.1.host.hostname", value = "test" },
		{ path = "node.1.os.architecture", value = "x86_64" },
		{ path = "node.1.os.type", value = "linux" },
		{ path = "node.1.os.distribution", value = "UBUNTU" },
                { path = "node.1.os.version", value = "20.04" },

		# beam document nodes 2 : database software
		{ path = "node.2.name", value = "dbswa" },
		{ path = "node.2.base", value = "dbhwa" },
		{ path = "node.2.type", value = "AceStandardDatabase" },
		{ path = "node.2.description", value = "software node generated by terraform BEAM resource" },
		{ path = "node.2.db.HOST", value = "localhost:3306:1" },
		{ path = "node.2.db.USER", value = "myuser" },
		{ path = "node.2.db.PASS", value = "mypass" },
		{ path = "node.2.db.BASE", value = "mybase" },

		# beam document node : duplicate database hardware
		{ path = "copy.node", "value" = "dbhwa" },
		{ path = "node.last.name", value = "dbhwb" },

		# beam document node : duplicate database software
		{ path = "copy.node", "value" = "dbswa" },
		{ path = "node.last.name", value = "dbswb" },
		{ path = "node.last.base", value = "dbhwb" },

		# beam document nodes 3 : web server hardware
		{ path = "copy.node", "value" = "dbhwa" },
		{ path = "node.last.name", value = "wshwa" },

		# beam document nodes 4 : web server software
		{ path = "copy.node", "value" = "dbswa" },
		{ path = "node.last.name", value = "wsswa" },
		{ path = "node.last.base", value = "wshwa" },
		{ path = "node.last.type", value = "Apache" },

		# beam document nodes 5 : web server hardware copy
		{ path = "copy.node", "value" = "wshwa" },
		{ path = "node.last.name", value = "wshwb" },

		# beam document nodes 6 : web server software copy
		{ path = "copy.node", "value" = "wsswa" },
		{ path = "node.last.name", value = "wsswb" },
		{ path = "node.last.base", value = "wshwb" },

		# beam document nodes 5a : web server hardware copy
		{ path = "copy.node", "value" = "wshwa" },
		{ path = "node.last.name", value = "wshwc" },

		# beam document nodes 6a : web server software copy
		{ path = "copy.node", "value" = "wsswa" },
		{ path = "node.last.name", value = "wsswc" },
		{ path = "node.last.base", value = "wshwc" },

		# beam document nodes 5b : web server hardware copy
		{ path = "copy.node", "value" = "wshwa" },
		{ path = "node.last.name", value = "wshwd" },

		# beam document nodes 6b : web server software copy
		{ path = "copy.node", "value" = "wsswa" },
		{ path = "node.last.name", value = "wsswd" },
		{ path = "node.last.base", value = "wshwd" },

		# beam document nodes 7 : load balancer hardware
		{ path = "copy.node", "value" = "dbhwa" },
		{ path = "node.last.name", value = "lbhwa" },

		# beam document nodes 8 : load balancer software 
		{ path = "copy.node", "value" = "dbswa" },
		{ path = "node.last.name", value = "lbswa" },
		{ path = "node.last.base", value = "lbhwa" },
		{ path = "node.last.type", value = "Haproxy" },

		# beam document nodes 5c : web server hardware copy
		{ path = "copy.node", "value" = "wshwa" },
		{ path = "node.last.name", value = "wshwe" },

		# beam document nodes 6c : web server software copy
		{ path = "copy.node", "value" = "wsswa" },
		{ path = "node.last.name", value = "wsswe" },
		{ path = "node.last.base", value = "wshwe" },

		# beam document nodes 5d : web server hardware copy
		{ path = "copy.node", "value" = "wshwa" },
		{ path = "node.last.name", value = "wshwf" },

		# beam document nodes 6d : web server software copy
		{ path = "copy.node", "value" = "wsswa" },
		{ path = "node.last.name", value = "wsswf" },
		{ path = "node.last.base", value = "wshwf" },

		# beam document nodes 17 : load balancer hardware copy
		{ path = "copy.node", "value" = "lbhwa" },
		{ path = "node.last.name", value = "lbhwb" },

		# beam document nodes 18 : load balancer software copy
		{ path = "copy.node", "value" = "lbswa" },
		{ path = "node.last.name", value = "lbswb" },
		{ path = "node.last.base", value = "lbhwb" },

		# beam document nodes 17 : load balancer hardware copy
		{ path = "copy.node", "value" = "lbhwa" },
		{ path = "node.last.name", value = "lbhwc" },

		# beam document nodes 18 : load balancer software copy
		{ path = "copy.node", "value" = "lbswa" },
		{ path = "node.last.name", value = "lbswc" },
		{ path = "node.last.base", value = "lbhwc" },

		# beam document relations
		{ path = "relation.node.dbhwa.hostname", value="node.wshwa" },
		{ path = "relation.node.dbhwa.hostname", value="node.wshwb" },
		{ path = "relation.node.dbhwa.hostname", value="node.wshwc" },
		{ path = "relation.node.dbhwa.hostname", value="node.wshwd" },
		{ path = "relation.node.dbhwa.hostname", value="node.wshwe" },
		{ path = "relation.node.dbhwa.hostname", value="node.wshwf" },
		{ path = "relation.node.dbhwb.hostname", value="node.wshwa" },
		{ path = "relation.node.dbhwb.hostname", value="node.wshwb" },
		{ path = "relation.node.dbhwb.hostname", value="node.wshwc" },
		{ path = "relation.node.dbhwb.hostname", value="node.wshwd" },
		{ path = "relation.node.dbhwb.hostname", value="node.wshwe" },
		{ path = "relation.node.dbhwb.hostname", value="node.wshwf" },
		{ path = "relation.node.wshwa.hostname", value="node.lbhwa" },
		{ path = "relation.node.wshwb.hostname", value="node.lbhwa" },
		{ path = "relation.node.wshwc.hostname", value="node.lbhwa" },
		{ path = "relation.node.wshwd.hostname", value="node.lbhwa" },
		{ path = "relation.node.wshwe.hostname", value="node.lbhwa" },
		{ path = "relation.node.wshwf.hostname", value="node.lbhwa" },
		{ path = "relation.node.wshwa.hostname", value="node.lbhwb" },
		{ path = "relation.node.wshwb.hostname", value="node.lbhwb" },
		{ path = "relation.node.wshwc.hostname", value="node.lbhwb" },
		{ path = "relation.node.wshwd.hostname", value="node.lbhwb" },
		{ path = "relation.node.wshwe.hostname", value="node.lbhwb" },
		{ path = "relation.node.wshwf.hostname", value="node.lbhwb" },
		{ path = "relation.node.lbhwa.hostname", value="node.lbhwc" },
		{ path = "relation.node.lbhwb.hostname", value="node.lbhwc" },
	]
}
