
resource "amenesik_beam" "mybeam" { 
	template = "template"
	program  = "mybeam-template"
	domain   = "openabal.com"
	region   = "any"
	category = "any"
	param    = "none"
	data     = [
		# beam document tags
		{ path = "tag.Title", value="My New Beam Document" },
		{ path = "tag.SubTitle", value="Generated by Terraform" },
		{ path = "tag.Author", value="Iain James Marshall" },
		{ path = "tag.Probe", value="memory-free" },
		{ path = "tag.Probe", value="disk-free" },

		# beam document nodes 1 : database hardware
		{ path = "node.1.name", value = "dbhwa" },
		{ path = "node.1.type", value = "Compute" },
		{ path = "node.1.host.num_cpus", value = "8" },
                { path = "node.1.host.mem_size", value = "32G" },
                { path = "node.1.host.disk_size", value = "i110G" },
		{ path = "node.1.os.distribution", value = "UBUNTU" },
                { path = "node.1.os.version", value = "20.04" },

		# beam document nodes 2 : database software
		{ path = "node.2.name", value = "dbswa" },
		{ path = "node.2.base", value = "dbhwa" },
		{ path = "node.2.type", value = "Database" },
		{ path = "node.2.db.HOST", value = "localhost:3306:1" },
		{ path = "node.2.db.USER", value = "myuser" },
		{ path = "node.2.db.PASS", value = "mypass" },
		{ path = "node.2.db.BASE", value = "mybase" },

		# beam document node : duplicate database hardware
		{ path = "copy.node", "value" = "dbhwa" },
		{ path = "node.last.name", value = "dbhwb" },

		# beam document node : duplicate database software
		{ path = "copy.node", "value" = "dbswa" },
		{ path = "node.last.name", value = "dbswb" },
		{ path = "node.last.base", value = "dbhwb" },

		# beam document nodes 3 : web server hardware
		{ path = "copy.node", "value" = "dbhwa" },
		{ path = "node.last.name", value = "wshwa" },

		# beam document nodes 4 : web server software
		{ path = "copy.node", "value" = "dbswa" },
		{ path = "node.last.name", value = "wsswa" },
		{ path = "node.last.base", value = "wshwa" },
		{ path = "node.last.type", value = "WebServer" },

		# beam document nodes 5 : web server hardware copy
		{ path = "copy.node", "value" = "wshwa" },
		{ path = "node.last.name", value = "wshwb" },

		# beam document nodes 6 : web server software copy
		{ path = "copy.node", "value" = "wsswa" },
		{ path = "node.last.name", value = "wsswb" },
		{ path = "node.last.base", value = "wshwb" },

		# beam document nodes 5a : web server hardware copy
		{ path = "copy.node", "value" = "wshwa" },
		{ path = "node.last.name", value = "wshwc" },

		# beam document nodes 6a : web server software copy
		{ path = "copy.node", "value" = "wsswa" },
		{ path = "node.last.name", value = "wsswc" },
		{ path = "node.last.base", value = "wshwc" },

		# beam document nodes 5b : web server hardware copy
		{ path = "copy.node", "value" = "wshwa" },
		{ path = "node.last.name", value = "wshwd" },

		# beam document nodes 6b : web server software copy
		{ path = "copy.node", "value" = "wsswa" },
		{ path = "node.last.name", value = "wsswd" },
		{ path = "node.last.base", value = "wshwd" },

		# beam document nodes 7 : load balancer hardware
		{ path = "copy.node", "value" = "dbhw" },
		{ path = "node.last.name", value = "lbhwa" },

		# beam document nodes 8 : load balancer software 
		{ path = "copy.node", "value" = "dbsw" },
		{ path = "node.last.name", value = "lbswa" },
		{ path = "node.last.base", value = "lbhwa" },
		{ path = "node.last.type", value = "LoadBalancer" },

		# beam document nodes 5c : web server hardware copy
		{ path = "copy.node", "value" = "wshwa" },
		{ path = "node.last.name", value = "wshwe" },

		# beam document nodes 6c : web server software copy
		{ path = "copy.node", "value" = "wsswa" },
		{ path = "node.last.name", value = "wsswe" },
		{ path = "node.last.base", value = "wshwe" },

		# beam document nodes 5d : web server hardware copy
		{ path = "copy.node", "value" = "wshwa" },
		{ path = "node.last.name", value = "wshwf" },

		# beam document nodes 6d : web server software copy
		{ path = "copy.node", "value" = "wsswa" },
		{ path = "node.last.name", value = "wsswf" },
		{ path = "node.last.base", value = "wshwf" },

		# beam document nodes 17 : load balancer hardware copy
		{ path = "copy.node", "value" = "lbhwa" },
		{ path = "node.last.name", value = "lbhwb" },

		# beam document nodes 18 : load balancer software copy
		{ path = "copy.node", "value" = "lbswa" },
		{ path = "node.last.name", value = "lbswb" },
		{ path = "node.last.base", value = "lbhwb" },

		# beam document nodes 17 : load balancer hardware copy
		{ path = "copy.node", "value" = "lbhwa" },
		{ path = "node.last.name", value = "lbhwc" },

		# beam document nodes 18 : load balancer software copy
		{ path = "copy.node", "value" = "lbswa" },
		{ path = "node.last.name", value = "lbswc" },
		{ path = "node.last.base", value = "lbhwc" },

		# beam document relations
		{ path = "relation.node.dbhwa.hostname", value="node.wshwa" },
		{ path = "relation.node.dbhwa.hostname", value="node.wshwb" },
		{ path = "relation.node.dbhwa.hostname", value="node.wshwc" },
		{ path = "relation.node.dbhwa.hostname", value="node.wshwd" },
		{ path = "relation.node.dbhwa.hostname", value="node.wshwe" },
		{ path = "relation.node.dbhwa.hostname", value="node.wshwf" },
		{ path = "relation.node.dbhwb.hostname", value="node.wshwa" },
		{ path = "relation.node.dbhwb.hostname", value="node.wshwb" },
		{ path = "relation.node.dbhwb.hostname", value="node.wshwc" },
		{ path = "relation.node.dbhwb.hostname", value="node.wshwd" },
		{ path = "relation.node.dbhwb.hostname", value="node.wshwe" },
		{ path = "relation.node.dbhwb.hostname", value="node.wshwf" },
		{ path = "relation.node.wshwa.hostname", value="node.lbhwa" },
		{ path = "relation.node.wshwb.hostname", value="node.lbhwa" },
		{ path = "relation.node.wshwc.hostname", value="node.lbhwa" },
		{ path = "relation.node.wshwd.hostname", value="node.lbhwa" },
		{ path = "relation.node.wshwe.hostname", value="node.lbhwa" },
		{ path = "relation.node.wshwf.hostname", value="node.lbhwa" },
		{ path = "relation.node.wshwa.hostname", value="node.lbhwb" },
		{ path = "relation.node.wshwb.hostname", value="node.lbhwb" },
		{ path = "relation.node.wshwc.hostname", value="node.lbhwb" },
		{ path = "relation.node.wshwd.hostname", value="node.lbhwb" },
		{ path = "relation.node.wshwe.hostname", value="node.lbhwb" },
		{ path = "relation.node.wshwf.hostname", value="node.lbhwb" },
		{ path = "relation.node.lbhwa.hostname", value="node.lbhwc" },
		{ path = "relation.node.lbhwb.hostname", value="node.lbhwc" },
	]
}
