
resource "amenesik_beam" "mybeam" { 
	template = "template"
	program  = "mybeam-template"
	domain   = "openabal.com"
	region   = "any"
	category = "any"
	param    = "none"
	data     = [
		# beam document tags
		{ path = "tag.Title", value="My New Beam Document" },
		{ path = "tag.SubTitle", value="Generated by Terraform" },
		{ path = "tag.Author", value="Iain James Marshall" },
		{ path = "tag.Probe", value="memory-free" },
		{ path = "tag.Probe", value="disk-free" },

		# beam document nodes 1
		{ path = "node.1.name", value = "hwn1" },
		{ path = "node.1.type", value = "Compute" },
		{ path = "node.1.host.num_cpus", value = "1" },
                { path = "node.1.host.mem_size", value = "2G" },
                { path = "node.1.host.disk_size", value = "10G" },
		{ path = "node.1.os.distribution", value = "UBUNTU" },
                { path = "node.1.os.version", value = "20.04" },
		# beam document nodes 2
		{ path = "node.2.name", value = "swn2" },
		{ path = "node.2.base", value = "hwn1" },
		{ path = "node.2.type", value = "Database" },
		{ path = "node.2.db.HOST", value = "localhost:3306:1" },
		{ path = "node.2.db.USER", value = "myuser" },
		{ path = "node.2.db.PASS", value = "mypass" },
		{ path = "node.2.db.BASE", value = "mybase" },

		# beam document nodes 3
		{ path = "copy.node", "value" = "1" },
		{ path = "node.3.name", value = "hwn3" },

		# beam document nodes 4
		{ path = "copy.node", "value" = "2" },
		{ path = "node.4.name", value = "swn4" },
		{ path = "node.4.base", value = "hwn3" },
		{ path = "node.4.type", value = "WebServer" },

		# beam document nodes 5
		{ path = "copy.node", "value" = "1" },
		{ path = "node.5.name", value = "hwn5" },

		# beam document nodes 6
		{ path = "copy.node", "value" = "2" },
		{ path = "node.6.name", value = "swn6" },
		{ path = "node.6.base", value = "hwn5" },

		# beam document nodes 7
		{ path = "copy.node", "value" = "1" },
		{ path = "node.7.name", value = "hwn7" },

		# beam document nodes 8
		{ path = "copy.node", "value" = "2" },
		{ path = "node.8.name", value = "swn8" },
		{ path = "node.8.base", value = "hwn7" },
		{ path = "node.8.type", value = "LoadBalancer" },

		# beam document relations
		{ path = "relation.node.1.hostname", value="node.3" },
		{ path = "relation.node.1.hostname", value="node.5" },
		{ path = "relation.node.3.hostname", value="node.7" },
		{ path = "relation.node.5.hostname", value="node.7" },
	]
}
